apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-mew-config
  namespace: dev
  labels:
    app.kubernetes.io/name: contoso-air-mew
    kubernetes.azure.com/generator: devhub
data:
  AZURE_SEARCH_RESOURCE_ID: /subscriptions/d88c020a-2180-43da-91a2-f6cc01f25946/resourceGroups/mew11-azure-ai-workshop-rg/providers/Microsoft.Search/searchServices/aiworkshop-search-rmsgmwk472oxi